houseSample<- read.csv.sql("household_power_consumption.txt", sql = "select * from file WHERE Date = '1/2/2007' or Date = '2/2/2007'", header = TRUE, sep = ";")
x<- paste(houseSample$Date,houseSample$Time)
houseSample$Time <- strptime(x,format = "%d/%m/%Y %H:%M:%S")
png (filename = "plot1.png", width = 480, height = 480, units = "px")
hist(houseSample$Global_active_power,col="red",xlab="Global Active Power (killowatts)",ylab="Frequency",main="Global Active Power")
dev.off()
